<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FirebaseAdmin" Version="3.1.0" />
        <PackageReference Include="Google.Cloud.Firestore" Version="3.10.0" />

        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CinemaCatalog.Application\CinemaCatalog.Application.csproj"/>
        <ProjectReference Include="..\CinemaCatalog.Domain\CinemaCatalog.Domain.csproj"/>
    </ItemGroup>

</Project>